[project]
name = "cybershield-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apprise>=1.9.8",
    "bcrypt>=5.0.0",
    "deepface>=0.0.99",
    "easyocr>=1.7.2",
    "fastapi>=0.135.1",
    "numpy>=2.4.3",
    "opencv-python>=4.13.0.92",
    "pandas>=2.3.3",
    "plotly>=6.6.0",
    "pydeck>=0.9.1",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.48",
    "streamlit>=1.55.0",
    "tf-keras>=2.20.1",
    "twilio>=9.10.3",
    "ultralytics>=8.4.22",
    "uvicorn>=0.41.0",
]
